file_path = "/home/wb/Documents/furniture/"
temp_path = "/home/wb/Documents/temp.txt"
posting_list_path = "/home/wb/Documents/furnito/invert_index/posting_list.json"
vector_space_path = "/home/wb/Documents/furnito/invert_index/vector_space.csv"
probability_space_path = "/home/wb/Documents/furnito/invert_index/probability_space.csv"
